"""
GraphML Viewer - A comprehensive tool for visualizing LightRAG knowledge graphs

This package provides tools for loading, analyzing, and visualizing GraphML files
generated by LightRAG, with support for interactive exploration and customizable layouts.
"""

__version__ = "0.1.0"

from .analysis import GraphAnalyzer
from .graph_loader import GraphMLLoader

# Import visualizer and interactive modules with optional dependencies
try:
    from .visualizer import GraphVisualizer

    _VISUALIZER_AVAILABLE = True
except ImportError:
    _VISUALIZER_AVAILABLE = False

try:
    from .interactive import InteractiveViewer

    _INTERACTIVE_AVAILABLE = True
except ImportError:
    _INTERACTIVE_AVAILABLE = False

__all__ = [
    "GraphMLLoader",
    "GraphAnalyzer",
]

if _VISUALIZER_AVAILABLE:
    __all__.append("GraphVisualizer")

if _INTERACTIVE_AVAILABLE:
    __all__.append("InteractiveViewer")
